version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=hospital_sys
      - DB_USER=root
      - DB_PASS=strong_password

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=strong_password
      - MYSQL_DATABASE=hospital_sys
    volumes:
      - mysql_data:/var/lib/mysql
      - ./query.sql:/docker-entrypoint-initdb.d/query.sql

volumes:
  mysql_data: 